language: bash
services: docker
before_install:
  - cd RestWithSpringBootDockerUdemy
  - echo "Estamos na base do Docker!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push mvcalicy/mysql-rest-with-spring-boot-udemy;
    docker push mvcalicy/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false